/**
 * String templates for the files we generate from scratch for each
 * deploy (everything not in `manifest.ts`).
 *
 * The generated project is a self-contained Next.js 15 app that
 * renders the inlined `SiteSpec` via `<SiteRenderer/>`. It has no
 * dependency on Blaze itself once shipped.
 */
import type { SiteSpec } from "@/builder/types";

const BLAZE_DEPLOY_PACKAGE_JSON = `{
  "name": "blaze-generated-site",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@gsap/react": "^2.1.2",
    "@react-three/drei": "^10.0.0",
    "@react-three/fiber": "^9.0.0",
    "atropos": "^2.0.2",
    "clsx": "^2.1.1",
    "framer-motion": "^11.18.0",
    "gsap": "^3.13.0",
    "lenis": "^1.1.20",
    "maath": "^0.10.8",
    "next": "15.1.11",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-responsive": "^10.0.0",
    "tailwind-merge": "^2.6.0",
    "three": "^0.171.0",
    "three-stdlib": "^2.36.1",
    "zustand": "^5.0.3"
  },
  "devDependencies": {
    "@types/node": "^22.10.5",
    "@types/react": "^19.0.7",
    "@types/react-dom": "^19.0.3",
    "@types/three": "^0.171.0",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.5.1",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.7.3"
  },
  "engines": {
    "node": "22.x"
  }
}
`;

const BLAZE_DEPLOY_NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["three"],
  images: { unoptimized: true },
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: true },
};

export default nextConfig;
`;

const BLAZE_DEPLOY_VERCEL_JSON = `{
  "framework": "nextjs",
  "buildCommand": "next build"
}
`;

const BLAZE_DEPLOY_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
`;

const BLAZE_DEPLOY_LAYOUT_TSX = `import "./globals.css";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "{{SITE_TITLE}}",
  description: "Built with Blaze.",
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="min-h-screen bg-[#0a0a0a] text-[#fafafa] antialiased">
        {children}
      </body>
    </html>
  );
}
`;

const BLAZE_DEPLOY_PAGE_TSX = `"use client";

import { SiteRenderer } from "@/builder/components/SiteRenderer";
import type { SiteSpec } from "@/builder/types";

const spec: SiteSpec = {{INLINED_SPEC}};

export default function Page() {
  return <SiteRenderer spec={spec} />;
}
`;

const BLAZE_DEPLOY_GITIGNORE = `node_modules
.next
.vercel
.env*.local
.DS_Store
`;

const BLAZE_DEPLOY_README = `# {{SITE_TITLE}}

This is a [Next.js](https://nextjs.org/) site generated by [Blaze](https://github.com/nitishmeswal/Blaze).

## Run locally

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

Then open <http://localhost:3000>.

## Deploy

The included \`vercel.json\` declares \`framework: nextjs\`. Push to a Git repo Vercel can read, or run \`vercel\` from the project root.
`;

/**
 * Replace single-curly-brace placeholders only — keeps it safe to
 * have JSX braces in the surrounding template.
 */
function template(raw: string, vars: Record<string, string>) {
  return Object.entries(vars).reduce(
    (out, [k, v]) => out.split(`{{${k}}}`).join(v),
    raw
  );
}

export function packageJsonFor(): string {
  return BLAZE_DEPLOY_PACKAGE_JSON;
}

export function nextConfigFor(): string {
  return BLAZE_DEPLOY_NEXT_CONFIG;
}

export function vercelJsonFor(): string {
  return BLAZE_DEPLOY_VERCEL_JSON;
}

export function tsconfigFor(): string {
  return BLAZE_DEPLOY_TSCONFIG;
}

export function gitignoreFor(): string {
  return BLAZE_DEPLOY_GITIGNORE;
}

export function layoutTsxFor(spec: SiteSpec): string {
  return template(BLAZE_DEPLOY_LAYOUT_TSX, {
    SITE_TITLE: jsString(spec.meta?.title ?? "Untitled Blaze site"),
  });
}

export function pageTsxFor(spec: SiteSpec): string {
  return template(BLAZE_DEPLOY_PAGE_TSX, {
    INLINED_SPEC: JSON.stringify(spec, null, 2),
  });
}

export function readmeFor(spec: SiteSpec): string {
  return template(BLAZE_DEPLOY_README, {
    SITE_TITLE: spec.meta?.title ?? "Blaze site",
  });
}

/**
 * Quote a JS-string-safe value (escape backslashes and quotes). Used
 * for inlining values into source-code templates.
 */
function jsString(raw: string): string {
  return raw.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
